'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  vaultPath:    ()      => ipcRenderer.invoke('vault:path'),
  vaultInfo:    ()      => ipcRenderer.invoke('vault:info'),
  readIndex:    ()      => ipcRenderer.invoke('vault:index'),
  readPage:     (id)    => ipcRenderer.invoke('page:read', id),
  writePage:    (doc)   => ipcRenderer.invoke('page:write', doc),
  writePageSync:(doc)   => ipcRenderer.sendSync('page:writeSync', doc),
  writeConflict:(doc)   => ipcRenderer.invoke('page:writeConflict', doc),
  deletePage:   (id)    => ipcRenderer.invoke('page:delete', id),
  trashCount:   ()      => ipcRenderer.invoke('trash:count'),
  emptyTrash:   ()      => ipcRenderer.invoke('trash:empty'),
  revealTrash:  ()      => ipcRenderer.invoke('trash:reveal'),
  listFolders:  ()      => ipcRenderer.invoke('folder:list'),
  createFolder: (n)     => ipcRenderer.invoke('folder:create', n),
  renameFolder: (p)     => ipcRenderer.invoke('folder:rename', p),
  deleteFolder: (n)     => ipcRenderer.invoke('folder:delete', n),
  saveAsset:    (p)     => ipcRenderer.invoke('asset:save', p),
  cleanAssets:  (keep)  => ipcRenderer.invoke('assets:clean', keep),
  revealVault:  ()      => ipcRenderer.invoke('vault:reveal'),
  chooseVault:  ()      => ipcRenderer.invoke('vault:choose'),
  exportPng:    (p)     => ipcRenderer.invoke('export:png', p),
  exportText:   (p)     => ipcRenderer.invoke('file:exportText', p),
  importText:   (p)     => ipcRenderer.invoke('file:importText', p || {}),
  openExternal: (u)     => ipcRenderer.invoke('shell:open', u),
  printPdf:     (p)     => ipcRenderer.invoke('pdf:print', p),
  onMenu: (channel, fn) => ipcRenderer.on(channel, (_e, payload) => fn(payload)),
});
